# Используем образ дистрибутив линукс Alpine с версией Node -14 Node.js
FROM node:22-alpine

# Указываем нашу рабочую дерикторию
WORKDIR /app

# Копируем package файлы и устанавливаем все зависимости для сборки
COPY package.json package-lock.json ./
RUN npm ci && npm cache clean --force

# Копируем оставшееся приложение в контейнер
COPY . .

ARG DATABASE_URL="postgresql://user:pass@localhost:5432/db?schema=public"
ENV DATABASE_URL=${DATABASE_URL}

# Генерируем Prisma клиент
RUN npx prisma generate

RUN npm run build

# Открываем порт 3000 в нашем контейнере
EXPOSE 3000

# Запускаем сервер
CMD [ "npm", "start" ]

